# Generated by Django 6.0.1 on 2026-03-24 11:20

import apps.configuracoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracoesWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instancia', models.CharField(default='', max_length=100)),
                ('instancia_id', apps.configuracoes.models.EncryptedField(default='')),
                ('token', apps.configuracoes.models.EncryptedField()),
                ('client_token', apps.configuracoes.models.EncryptedField(blank=True, null=True)),
                ('url_base', models.URLField(max_length=2000)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração API Whatsapp',
                'verbose_name_plural': 'Configurações API Whatsapp',
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('ativo',), name='unique_config_whatsapp_ativa')],
            },
        ),
    ]
