# Generated by Django 6.0.1 on 2026-02-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracoesWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instancia', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=255)),
                ('client_token', models.CharField(blank=True, max_length=255, null=True)),
                ('url_base', models.URLField(max_length=2000)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração API Whatsapp',
                'verbose_name_plural': 'Configurações API Whatsapp',
            },
        ),
    ]
