# Generated by Django 6.0.1 on 2026-02-06 16:09

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoeswhatsapp',
            name='client_token',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracoeswhatsapp',
            name='token',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
        migrations.AddConstraint(
            model_name='configuracoeswhatsapp',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('ativo',), name='unique_config_whatsapp_ativa'),
        ),
    ]
