# Generated by Django 6.0.1 on 2026-02-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_alter_configuracoeswhatsapp_client_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracoeswhatsapp',
            name='instancia',
        ),
        migrations.AddField(
            model_name='configuracoeswhatsapp',
            name='nome_instancia',
            field=models.CharField(default='padrao', max_length=100),
        ),
    ]
