# Generated by Django 6.0.1 on 2026-02-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_remove_configuracoeswhatsapp_instancia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoeswhatsapp',
            name='nome_instancia',
            field=models.CharField(default='', max_length=100),
        ),
    ]
