# Generated by Django 6.0.1 on 2026-02-06 22:22

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0004_alter_configuracoeswhatsapp_nome_instancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracoeswhatsapp',
            name='instancia_id',
            field=fernet_fields.fields.EncryptedTextField(default=''),
        ),
    ]
