# Generated by Django 6.0.1 on 2026-03-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('categoria', models.CharField(blank=True, null=True, verbose_name='Categoria')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código Produto')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Venda')),
                ('quantidade_estoque', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Estoque')),
                ('estoque_minimo', models.PositiveBigIntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('unidade_medida', models.CharField(default='un', max_length=20, verbose_name='Unidade de Medida')),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fornecedor')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/imagens/', verbose_name='Imagem do Produto')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Barras')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
